routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{primary_tag}/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /auteurs/{slug}/
